version: '3'
services:
  app:
    container_name: docker-vue-test
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: "npm run serve"
